<?php

namespace app\models\query;

use app\models\view\VideoMV;
use yii\db\ActiveQuery;

class VideoQuery extends ActiveQuery
{
    /**
     * @inheritDoc
     */
    public function __construct()
    {
        parent::__construct(VideoMV::class);
    }

    /**
     * @inheritDoc
     */
    public function prepare($builder)
    {
        $simple_mode_field = $this->checkAndRewrieOrder();
        
        if ($simple_mode_field) {
            $this->checkAndRewrieOffset($simple_mode_field);
        }

        return parent::prepare($builder);
    }

    private function checkAndRewrieOrder()
    {
        $simple_mode = false;
        if (count($this->orderBy) == 1) {
            if (isset($this->orderBy['views'])) {
                $this->orderBy['rows_views'] = $this->orderBy['views'];
                unset($this->orderBy['views']);
                $simple_mode = 'rows_views';
            }

            if (isset($this->orderBy['time_add'])) {
                $this->orderBy['rows_time_add'] = $this->orderBy['time_add'];
                unset($this->orderBy['time_add']);
                $simple_mode = 'rows_time_add';
            }
        }
        return $simple_mode;
    }
    
    private function checkAndRewrieOffset($field_name)
    {
        if ($this->offset) {
            $this->andWhere(['>=', $field_name, $this->offset]);
            $this->offset = null;
        }
    }

    /**
     * @inheritDoc
     */
    public function populate($rows)
    {
        return parent::populate($rows); // TODO: Change the autogenerated stub
    }



    /** Just for autocomplete */
    
    /**
     * @inheritDoc
     * @return VideoMV|array|null
     */
    public function one($db = null)
    {
        return parent::one($db);
    }

    /**
     * @inheritDoc
     * @return VideoMV[]|array
     */
    public function all($db = null)
    {
        return parent::all($db);
    }


}